# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install
      - name: Build Website
        run: npm run build
      # https://github.com/yizhoumo/setup-ossutil
      # - uses: manyuanrong/setup-ossutil@v2.0
      #   with:
      #     endpoint: "oss-cn-hangzhou.aliyuncs.com"
      #     access-key-id: ${{secrets.ACCESS_KEY_ID}}
      #     access-key-secret: ${{secrets.ACCESS_KEY_SECRET}}
      # - run: ossutil cp -rf dist oss://higress-website-cn-hangzhou/
      # 部署到 github Page
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2